### ISSUE TITLE
Problem with older versions

### ISSUE THREAD

**Issue by GDmac** [EllisLab/EE-Language-English#4]
Hello EllisLab,
In git i notice that some lines like ``daylight_savings_time `` and ``localization_is_site_default``
are being dropped in 2.9. How to proceed?

## Update translation tip
ps. I'm pulling the dutch language thru the translation utility in the CP.
In the translate.php view-file i modified the display when a value for a key is empty.
e.g. add a ``*`` in front of the input, and copy over the english value 

also in ``translation_save()`` remove the extra space after the key =>
e.g. ``$str .= '\''.$key.'\' =>'."\n".'\''.$val.'\''.",\n\n";``

**Comment by wesbaker** [comment]
@GDmac sorry for the super late response, but if they're dropped they're no longer used, so delete them in your own translation.
