### ISSUE TITLE
Consistency across _lang.php files

### ISSUE THREAD

**Issue by ebeauchamps** [EllisLab/EE-Language-English#5]
I am updating the French translation. Some lang files are closed with:
```
?>
/* End of file xxx_lang.php */
/* Location: ./system/language/french/xxx_lang.php */
```
but some, more recent, are not.
Do we need to close the php tag and to add the last comment?

**Comment by wesbaker** [comment]
Don't close the PHP tag and the last comment can be there, and clearly we're inconsistent. Don't worry about adding it though, it's fine without it.
